name: Deploy Terraform

on:
  workflow_dispatch:
    inputs:
      instanceName:
        description: 'Name of the VM'
        required: true
      location:
        description: 'Azure region'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Log Inputs
        run: |
          echo "Instance Name: ${{ github.event.inputs.instanceName }}"
          echo "Location: ${{ github.event.inputs.location }}"
          echo "ARM_CLIENT_ID: ${ARM_CLIENT_ID}"
          echo "ARM_SUBSCRIPTION_ID: ${ARM_SUBSCRIPTION_ID}"
          echo "ARM_TENANT_ID: ${ARM_TENANT_ID}"
          echo "ARM_CLIENT_SECRET: ${ARM_CLIENT_SECRET}"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="vm_name=${{ github.event.inputs.instanceName }}" -var="location=${{ github.event.inputs.location }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="vm_name=${{ github.event.inputs.instanceName }}" -var="location=${{ github.event.inputs.location }}"
